<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.i360day</groupId>
	<artifactId>spring-cloud-invoker-parent</artifactId>
	<version>0.0.1</version>
	<packaging>pom</packaging>

	<name>spring-cloud-invoker-parent</name>
	<url>http://maven.apache.org</url>

	<modules>
		<!--dependencies-->
		<module>spring-invoker-dependencies</module>
		<!--boot-->
		<module>spring-boot-invoker-annotations</module>
		<module>spring-boot-invoker-core</module>
		<module>spring-boot-invoker-hystrix</module>
		<module>spring-boot-starter-invoker</module>
		<module>spring-boot-starter-amqp-invoker</module>
		<module>spring-boot-starter-redis-invoker</module>
		<module>spring-boot-starter-websocket-invoker</module>
		<!--cloud-->
		<module>spring-cloud-starter-invoker</module>
		<!--sample-->
		<module>spring-invoker-sample</module>
	</modules>

	<!--阿里云-->
	<distributionManagement>
		<repository>
			<id>public</id>
			<name>maven-releases</name>
			<url>https://maven.aliyun.com/repository/public</url>
		</repository>
		<snapshotRepository>
			<id>maven-snapshots</id>
			<name>maven-snapshots</name>
			<url>https://maven.aliyun.com/repository/snapshots</url>
		</snapshotRepository>
	</distributionManagement>

</project>
