<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.i360day</groupId>
		<artifactId>spring-invoker-sample</artifactId>
		<version>1.0.0</version>
	</parent>

	<groupId>com.i360day</groupId>
	<artifactId>spring-boot-invoker-redis-sample</artifactId>
	<description>test version</description>
	<packaging>pom</packaging>
	<version>1.0.0</version>

	<modules>
		<module>spring-boot-facade-redis-sample</module>
		<module>spring-boot-service-redis-sample</module>
		<module>spring-boot-client-redis-sample</module>
	</modules>

	<dependencies>

		<dependency>
			<groupId>com.i360day</groupId>
			<artifactId>spring-boot-starter-redis-invoker</artifactId>
		</dependency>

<!--		<dependency>-->
<!--			<groupId>org.redisson</groupId>-->
<!--			<artifactId>redisson-spring-boot-starter</artifactId>-->
<!--			<version>3.14.1</version>-->
<!--		</dependency>-->

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.74</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>
	</dependencies>
</project>
