<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>spring-invoker-dependencies</artifactId>
		<groupId>com.i360day</groupId>
		<version>3.0.4</version>
		<relativePath>../spring-invoker-dependencies</relativePath>
	</parent>

	<groupId>com.i360day</groupId>
	<artifactId>spring-boot-invoker-core</artifactId>
	<description>Core code package</description>
	<packaging>jar</packaging>
	<version>${spring.boot.invoker.core}</version>

	<name>spring-boot-invoker-core</name>
	<url>https://gitee.com/liju023/spring-cloud-invoker-parent</url>

	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>actable</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>liju023</name>
			<email>liju023@163.com</email>
			<organization>liju023</organization>
			<url>https://gitee.com/liju023/spring-cloud-invoker-parent</url>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:git@gitee.com:liju023/spring-cloud-invoker-parent.git</connection>
		<developerConnection>scm:git:git@gitee.com:liju023/spring-cloud-invoker-parent.git</developerConnection>
		<url>https://gitee.com/liju023/spring-cloud-invoker-parent</url>
		<tag>${version}</tag>
	</scm>

	<dependencies>
		<dependency>
			<groupId>com.i360day</groupId>
			<artifactId>spring-boot-invoker-annotations</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
			<version>${maven.spring.boot.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<version>${maven.spring.boot.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents.client5</groupId>
			<artifactId>httpclient5</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>

		<!-- spring security -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>
	</dependencies>
</project>
