server:
  port: 8761

spring:
  security:
    basic:
      enabled: true
    user:
      name: eureka
      password: eureka

eureka:
  server:
    enable-self-preservation: false #关闭自我保护
    #eviction-interval-timer-in-ms: 10 #清理时间
  instance:
    hostname: localhost
    preferIpAddress: true
    prefer-ip-address: true #使用IP注册,不指定时默认用用户名注册
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false